import { contextBridge, ipcRenderer } from "electron";
const allowed = new Set([
  "setup:status",
  "setup:create",
  "setup:branding",
  "session:staff",
  "session:current",
  "session:permissions",
  "session:signIn",
  "session:signOut",
  "staff:list",
  "staff:create",
  "staff:archive",
  "staff:resetPin",
  "permissions:list",
  "permissions:update",
  "members:list",
  "members:get",
  "members:save",
  "members:archive",
  "members:history",
  "members:choosePhoto",
  "members:chooseDocument",
  "members:openDocument",
  "faces:status",
  "faces:memberStatus",
  "faces:enroll",
  "faces:remove",
  "documents:requirements",
  "documents:addRequirement",
  "documents:archiveRequirement",
  "plans:list",
  "plans:save",
  "plans:archive",
  "memberships:list",
  "memberships:assign",
  "memberships:action",
  "memberships:freezeHistory",
  "attendance:list",
  "attendance:checkIn",
  "attendance:checkOut",
  "payments:list",
  "payments:record",
  "payments:refund",
  "payments:receipt",
  "dashboard:get",
  "backup:status",
  "backup:export",
  "backup:import",
  "backup:factoryReset",
  "settings:get",
  "settings:update",
  "settings:chooseLogo",
  "preferences:get",
  "preferences:update",
  "reports:get",
  "reports:export",
  "export:csv",
  "audit:list",
  "kiosk:checkInByCode",
  "kiosk:recognizeFace",
  "kiosk:enterPresentation",
  "kiosk:exitPresentation",
]);
contextBridge.exposeInMainWorld("openGym", {
  invoke: (channel: string, payload?: unknown) => {
    if (!allowed.has(channel))
      return Promise.resolve({
        ok: false,
        error: { code: "NOT_ALLOWED", message: "Action not allowed" },
      });
    return ipcRenderer.invoke(channel, payload);
  },
});
